### ISSUE TITLE
fixing tables

### ISSUE THREAD

**Issue by vnuke** [inf3500/labo2#1]
pour réparer les bug d'affichage du markdown pour les tableau

**Comment by pierrelanglois** [comment]
Donc ... résolu en ajoutant des barres verticales (|) avant et à la fin de chaque ligne ? OK+merci.
Mais ça marche correctement dans le fichier readme.md sans ces anté- et post-barres (voir la section barème de correction) ... pourquoi ?

**Comment by vnuke** [comment]
Honnêtement je n'en ai pas la moindre idée...
je dirais que c'est parce qu'il y avait de l'ambiguité, mais je n'en suis pas sur
